/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/transacoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editar"];
        post?: never;
        delete: operations["excluir"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferencia-cenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultarPreferencia"];
        put: operations["salvarPreferencia"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editar_1"];
        post?: never;
        delete: operations["excluir_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta-aporte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultar_3"];
        put: operations["definir"];
        post?: never;
        delete: operations["remover"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investimentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editar_2"];
        post?: never;
        delete: operations["excluir_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar"];
        put?: never;
        post: operations["criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes/parcelada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["parcelar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes-recorrentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_1"];
        put?: never;
        post: operations["criar_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_2"];
        put?: never;
        post: operations["criar_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_3"];
        put?: never;
        post: operations["criar_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_4"];
        put?: never;
        post: operations["criar_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_5"];
        put?: never;
        post: operations["criar_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginComGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes/{id}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["confirmar"];
        trace?: never;
    };
    "/api/visao-geral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vencimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultar_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saldo-disponivel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultarSaldo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previsao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultar_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fluxo-caixa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultar_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultar_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consultarUsuarioLogado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transacoes-recorrentes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["desativar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["excluir_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["excluir_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequisicaoDeTransacao: {
            /** Format: int64 */
            contaId: number;
            /** Format: int64 */
            categoriaId: number;
            descricao: string;
            valor: number;
            /** @enum {string} */
            tipo: "RECEITA" | "DESPESA";
            /** Format: date */
            dataPrevista: string;
            /** Format: date */
            dataEfetivacao?: string;
        };
        RespostaTransacao: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            contaId?: number;
            /** Format: int64 */
            categoriaId?: number;
            descricao?: string;
            valor?: number;
            /** @enum {string} */
            tipo?: "RECEITA" | "DESPESA";
            /** Format: date */
            dataPrevista?: string;
            /** Format: date */
            dataEfetivacao?: string;
            /** @enum {string} */
            status?: "PREVISTA" | "CONFIRMADA" | "ATRASADA";
            /** Format: uuid */
            grupoParcelamentoId?: string;
            /** Format: int32 */
            numeroParcela?: number;
            /** Format: int32 */
            totalParcelas?: number;
        };
        RequisicaoDePreferenciaCenario: {
            percentualAjusteReceita: number;
            percentualAjusteDespesa: number;
        };
        RespostaPreferenciaCenario: {
            percentualAjusteReceita?: number;
            percentualAjusteDespesa?: number;
        };
        RequisicaoDeMetaFinanceira: {
            nome: string;
            valorAtual?: number;
            valorObjetivo: number;
            /** Format: date */
            prazo?: string;
            descricao?: string;
        };
        RespostaMetaFinanceira: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            valorAtual?: number;
            valorObjetivo?: number;
            percentualConcluido?: number;
            valorRestante?: number;
            concluida?: boolean;
            /** Format: date */
            prazo?: string;
            /** Format: int64 */
            diasAtePrazo?: number;
            prazoVencido?: boolean;
            descricao?: string;
        };
        RequisicaoDeMetaAporte: {
            valor: number;
        };
        RespostaMetaAporte: {
            valor?: number;
            definida?: boolean;
        };
        RequisicaoDeInvestimento: {
            nome: string;
            /** @enum {string} */
            tipo: "RENDA_FIXA" | "ACOES" | "FIIS" | "CRIPTO" | "TESOURO";
            valorInvestido: number;
            rentabilidadeInformada?: number;
        };
        RespostaInvestimento: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            /** @enum {string} */
            tipo?: "RENDA_FIXA" | "ACOES" | "FIIS" | "CRIPTO" | "TESOURO";
            valorInvestido?: number;
            rentabilidadeInformada?: number;
        };
        RequisicaoDeParcelamento: {
            /** Format: int64 */
            contaId: number;
            /** Format: int64 */
            categoriaId: number;
            descricao: string;
            valorTotal: number;
            /** @enum {string} */
            tipo: "RECEITA" | "DESPESA";
            /** Format: date */
            dataDaPrimeiraParcela: string;
            /** Format: int32 */
            totalParcelas: number;
        };
        RequisicaoDeRecorrencia: {
            /** Format: int64 */
            contaId: number;
            /** Format: int64 */
            categoriaId: number;
            descricao: string;
            valor: number;
            /** @enum {string} */
            tipo: "RECEITA" | "DESPESA";
            /** @enum {string} */
            periodicidade: "SEMANAL" | "MENSAL" | "ANUAL";
            /** Format: int32 */
            diaDoMes?: number;
            /** Format: int32 */
            diaDaSemana?: number;
            /** Format: date */
            dataInicio: string;
            /** Format: date */
            dataFim?: string;
        };
        RespostaRecorrencia: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            contaId?: number;
            /** Format: int64 */
            categoriaId?: number;
            descricao?: string;
            valor?: number;
            /** @enum {string} */
            tipo?: "RECEITA" | "DESPESA";
            /** @enum {string} */
            periodicidade?: "SEMANAL" | "MENSAL" | "ANUAL";
            /** Format: int32 */
            diaDoMes?: number;
            /** Format: int32 */
            diaDaSemana?: number;
            /** Format: date */
            dataInicio?: string;
            /** Format: date */
            dataFim?: string;
            ativa?: boolean;
        };
        RequisicaoDeConta: {
            nome: string;
            /** @enum {string} */
            tipo: "CONTA_CORRENTE" | "CONTA_POUPANCA" | "CARTAO_CREDITO" | "CARTEIRA";
        };
        RespostaConta: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            /** @enum {string} */
            tipo?: "CONTA_CORRENTE" | "CONTA_POUPANCA" | "CARTAO_CREDITO" | "CARTEIRA";
            cartaoDeCredito?: boolean;
        };
        RequisicaoDeCategoria: {
            nome: string;
            /** @enum {string} */
            tipo: "RECEITA" | "DESPESA" | "AMBOS";
            corHex: string;
        };
        RespostaCategoria: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            /** @enum {string} */
            tipo?: "RECEITA" | "DESPESA" | "AMBOS";
            corHex?: string;
            padraoDoSistema?: boolean;
        };
        RequisicaoDeRegistro: {
            nome: string;
            email: string;
            senha: string;
        };
        RespostaAutenticacao: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            email?: string;
            token?: string;
            tipo?: string;
            /** Format: date-time */
            expiraEm?: string;
        };
        RequisicaoDeLogin: {
            email: string;
            senha: string;
        };
        RequisicaoDeLoginComGoogle: {
            idToken: string;
        };
        RespostaResumoDoMes: {
            /** Format: int32 */
            mes?: number;
            /** Format: int32 */
            ano?: number;
            receitasRealizadas?: number;
            receitasPrevistas?: number;
            despesasRealizadas?: number;
            despesasPrevistas?: number;
            totalReceitas?: number;
            totalDespesas?: number;
            saldoDoMes?: number;
        };
        RespostaVisaoGeral: {
            saldoDisponivel?: number;
            saldoRealizado?: number;
            mesAtual?: components["schemas"]["RespostaResumoDoMes"];
            proximosMeses?: components["schemas"]["RespostaResumoDoMes"][];
        };
        RespostaSaldo: {
            saldoDisponivel?: number;
            saldoRealizado?: number;
        };
        RespostaPrevisao: {
            /** @enum {string} */
            cenario?: "PROVAVEL" | "OTIMISTA" | "PESSIMISTA";
            percentualAjusteReceita?: number;
            percentualAjusteDespesa?: number;
            meses?: components["schemas"]["RespostaPrevisaoMensal"][];
        };
        RespostaPrevisaoMensal: {
            /** Format: int32 */
            mes?: number;
            /** Format: int32 */
            ano?: number;
            saldoInicial?: number;
            totalReceitasPrevistas?: number;
            totalDespesasPrevistas?: number;
            saldoProjetado?: number;
            transacoes?: components["schemas"]["RespostaTransacao"][];
        };
        RespostaCarteira: {
            totalInvestido?: number;
            rentabilidadeMediaPonderada?: number;
            /** Format: int32 */
            quantidade?: number;
            investimentos?: components["schemas"]["RespostaInvestimento"][];
        };
        RespostaFluxoDeCaixa: {
            saldoAnterior?: number;
            meses?: components["schemas"]["RespostaFluxoMensal"][];
        };
        RespostaFluxoMensal: {
            /** Format: int32 */
            mes?: number;
            /** Format: int32 */
            ano?: number;
            entradas?: number;
            saidas?: number;
            saldoDoMes?: number;
            saldoAcumulado?: number;
        };
        RespostaCalendario: {
            /** Format: int32 */
            mes?: number;
            /** Format: int32 */
            ano?: number;
            totalReceitas?: number;
            totalDespesas?: number;
            saldoDoMes?: number;
            dias?: components["schemas"]["RespostaDia"][];
        };
        RespostaDia: {
            /** Format: date */
            data?: string;
            totalReceitas?: number;
            totalDespesas?: number;
            saldoDoDia?: number;
            transacoes?: components["schemas"]["RespostaTransacao"][];
        };
        RespostaUsuario: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            email?: string;
            possuiSenha?: boolean;
            vinculadoAoGoogle?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    editar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeTransacao"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaTransacao"];
                };
            };
        };
    };
    excluir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    consultarPreferencia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaPreferenciaCenario"];
                };
            };
        };
    };
    salvarPreferencia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDePreferenciaCenario"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaPreferenciaCenario"];
                };
            };
        };
    };
    editar_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeMetaFinanceira"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaMetaFinanceira"];
                };
            };
        };
    };
    excluir_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    consultar_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaMetaAporte"];
                };
            };
        };
    };
    definir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeMetaAporte"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaMetaAporte"];
                };
            };
        };
    };
    remover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editar_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeInvestimento"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaInvestimento"];
                };
            };
        };
    };
    excluir_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listar: {
        parameters: {
            query?: {
                tipo?: "RECEITA" | "DESPESA";
                periodo?: "TODOS" | "MES_ATUAL" | "PROXIMOS_30_DIAS" | "PROXIMOS_90_DIAS";
                categoriaId?: number;
                contaId?: number;
                busca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaTransacao"][];
                };
            };
        };
    };
    criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeTransacao"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaTransacao"];
                };
            };
        };
    };
    parcelar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeParcelamento"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaTransacao"][];
                };
            };
        };
    };
    listar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaRecorrencia"][];
                };
            };
        };
    };
    criar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeRecorrencia"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaRecorrencia"];
                };
            };
        };
    };
    listar_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaMetaFinanceira"][];
                };
            };
        };
    };
    criar_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeMetaFinanceira"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaMetaFinanceira"];
                };
            };
        };
    };
    listar_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaCarteira"];
                };
            };
        };
    };
    criar_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeInvestimento"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaInvestimento"];
                };
            };
        };
    };
    listar_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaConta"][];
                };
            };
        };
    };
    criar_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeConta"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaConta"];
                };
            };
        };
    };
    listar_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaCategoria"][];
                };
            };
        };
    };
    criar_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeCategoria"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaCategoria"];
                };
            };
        };
    };
    registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeRegistro"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaAutenticacao"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeLogin"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaAutenticacao"];
                };
            };
        };
    };
    loginComGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequisicaoDeLoginComGoogle"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaAutenticacao"];
                };
            };
        };
    };
    confirmar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaTransacao"];
                };
            };
        };
    };
    consultar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaVisaoGeral"];
                };
            };
        };
    };
    consultar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaTransacao"][];
                };
            };
        };
    };
    consultarSaldo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaSaldo"];
                };
            };
        };
    };
    consultar_2: {
        parameters: {
            query?: {
                meses?: number;
                cenario?: "PROVAVEL" | "OTIMISTA" | "PESSIMISTA";
                ajusteReceita?: number;
                ajusteDespesa?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaPrevisao"];
                };
            };
        };
    };
    consultar_4: {
        parameters: {
            query?: {
                mesesPassados?: number;
                mesesFuturos?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaFluxoDeCaixa"];
                };
            };
        };
    };
    consultar_5: {
        parameters: {
            query?: {
                mes?: number;
                ano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaCalendario"];
                };
            };
        };
    };
    consultarUsuarioLogado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespostaUsuario"];
                };
            };
        };
    };
    desativar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    excluir_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    excluir_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
